# Generated by Django 4.2.4 on 2023-12-06 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataproduct', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnotherValuableData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('value', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'verbose_name_plural': 'DATA PRODUCT - Valuable data 2',
            },
        ),
        migrations.AlterModelOptions(
            name='valuabledata',
            options={'verbose_name_plural': 'DATA PRODUCT - Valuable data 1'},
        ),
    ]
