# Generated by Django 4.2.4 on 2023-12-06 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dataproduct', '0003_freedata'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FreeData',
            new_name='BasicData',
        ),
        migrations.AlterModelOptions(
            name='basicdata',
            options={'verbose_name_plural': 'DATA PRODUCT - Basic data'},
        ),
    ]
